licencia

diff --git a/xfce b/xfce
--- a/xfce
+++ b/xfce
@@ -1,7 +1,10 @@
 #!/bin/bash
+# Made by Sinfallas <sinfallas@yahoo.com>
+# Licence: GPL-2
 if [[ $USER != root ]]; then
-echo -e "\e[00;31mERROR: must be root\e[00m"
-exit 1
+	echo -e "\e[00;31mERROR: DEBES SER ROOT\e[00m"
+	exit 1
+fi
 fid-apt-repository -y ppa:xubuntu-dev/xfce-4.10
 apt -q update
 apt -y install xubuntu-desktop xfce4-composite-editor xfce-theme-manager xfce4-power-manager-plugins
